analyte: Chloride
skip_blank: false
process_blank_files_separatedly: false
image_size: 448
feature_extractor: resnet50
cnn_blocks: 3
network_model: zero_dawn
chosen_model: "best_model_3blocks_resnet50_img_size_448" #"best_model_2blocks_resnet50"
use_checkpoint: false
sweep_id: false

feature_extraction:
  vgg11:
    Alkalinity:
      feature_list:
        [features.2, features.5, features.10]
      receptive_field_dim: 15
      descriptor_depth   : 448
      cnn1_output_shape        : 98
    Chloride  :
      feature_list:
        [features.2, features.5, features.10, features.15, features.20]
      receptive_field_dim: 27
      descriptor_depth   : 1472
      cnn1_output_shape        : 86

  resnet50:
    Alkalinity:
      feature_list: null
      receptive_field_dim: null
      descriptor_depth   : null
      cnn1_output_shape        : null
    Chloride  :
      feature_list:
        [relu, layer1.2.relu_2 , layer2.3.relu_2] #, layer3.5.relu_2] #, layer4.2.relu_2]
      receptive_field_dim: 0
      descriptor_depth   :  832 #320 #1856 #320 #832 # 3904
      cnn1_output_shape   : 224 #112

models:
  max_epochs: 400
  learning_rate: 0.001
  learning_rate_patience: 5
  gradient_clipping: 0.5
  loss_function: wasserstein
  optimizer: sgd
  batch_size: 150
  batch_normalization: true

statistical_analysis:
  images_to_evaluate: test