program: models_sweep.py
method: bayes
name: Chloride
metric:
  name: Loss/Val
  goal: minimize
  name: MAE/Val/Epoch
  goal: minimize
  name: MAPE/Val/Epoch
  goal: minimize
parameters:
  batch_size:
    min: 200
    max: 20000
  lr:
    max: 0.0001
    min: 0.0000000000001
  gradient_clip:
    min: 0.1
    max: 0.6
  dropout_upper_layers:
    max: 0.5
    min: 0.3
  dropout_middle_layers:
    max: 0.3
    min: 0.15
  dropout_lower_layers:
    max: 0.15
    min: 0.0

  # weight_decay:
  #   max: 0.1e-1
  #   min: 0.1e-5
  # optimizer:
  #   value: sgd
  # criterion:
  #   value: Loss/Train
  #criterion:
   # value: Loss/Val