program: models_sweep.py
method: bayes
name: Chloride
metric:
  name: Loss/Val
  goal: minimize
  name: MAE/Val/Epoch
  goal: minimize
  name: MAPE/Val/Epoch
  goal: minimize
parameters:
  lr:
    max: 0.0001
    min: 0.0000000000001
  gradient_clip:
    min: 0.1
    max: 0.6
  dropout_upper_layers:
    max: 0.5
    min: 0.3
  dropout_middle_layers:
    max: 0.3
    min: 0.15
  dropout_lower_layers:
    max: 0.15
    min: 0.0
  num_hidden_layers:
    max: 9
    min: 5
  input_layer:
    value:   512
  layer_13:
    values: [ 512, 256, 128,  ]
  layer_12:
    values: [ 512, 256, 128,  ]
  layer_11:
    values: [ 512, 256, 128,  ]
  layer_10:
    values: [ 512, 256, 128,  ]
  layer_9 :
    values: [ 512, 256, 128, ]
  layer_8 :
    values: [ 512, 256, 128, ]
  layer_7 :
    values: [ 512, 256, 128, ]
  layer_6 :
    values: [ 256, 128, 64,  ]
  layer_5 :
    values: [ 256, 128, 64,  ]
  layer_4 :
    values: [ 128, 64, 32, ]
  layer_3 :
    values: [ 128, 64, 32, ]
  layer_2 :
    values: [ 16,   8,   4,  2 ]
  layer_1 :
    values: [ 16,   8,   4,  2 ]
  output_layer:
    value: 1

  # weight_decay:
  #   max: 0.1e-1
  #   min: 0.1e-5
